/*
 * Note: this file originally auto-generated by mib2c using
 *  $
 */
#ifndef BRIDGETABLE_H
#define BRIDGETABLE_H

/*
 * function declarations 
 */
void            init_bridgeTable(void);
void            initialize_table_bridgeTable(void);
Netsnmp_Node_Handler bridgeTable_handler;
Netsnmp_First_Data_Point bridgeTable_get_first_data_point;
Netsnmp_Next_Data_Point bridgeTable_get_next_data_point;
#endif                          /* BRIDGETABLE_H */
