/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef BRIDGETABLE_H
#define BRIDGETABLE_H

#define BRIDGE_TABLE_INDEX_NUM	2

void            init_bridgeTable(void);
FindVarMethod   var_bridgeTable;
WriteMethod     write_bridgeTable;

extern long ifInfoTable_getIdByname(char *ifName);

#endif                          /* BRIDGETABLE_H */
