/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef DEVINFO_H
#define DEVINFO_H

/*
 * function declarations 
 */
void            init_devinfo(void);
Netsnmp_Node_Handler handle_hostname;
Netsnmp_Node_Handler handle_systemtype;
Netsnmp_Node_Handler handle_kernelVersion;
Netsnmp_Node_Handler handle_uptime;
Netsnmp_Node_Handler handle_ipforward;
Netsnmp_Node_Handler handle_cpu;
Netsnmp_Node_Handler handle_mem;


typedef struct devinfo_node_data
{
	char hostname[32];
	char systemtype[32];
	char kernelver[32];
	long uptime;
	unsigned int ipforward;
	unsigned int old_ipforward;
	unsigned int cpu;
	unsigned int mem;
}devinfo_node_data_t;
#endif                          /* DEVINFO_H */
