/*
 * Note: this file originally auto-generated by mib2c using
 *  $
 */
#ifndef IFINFOTABLE_H
#define IFINFOTABLE_H

/*
 * function declarations 
 */

#define MAX_IFNUM	32

void            init_ifInfoTable(void);
void            initialize_table_ifInfoTable(void);
Netsnmp_Node_Handler ifInfoTable_handler;
Netsnmp_First_Data_Point ifInfoTable_get_first_data_point;
Netsnmp_Next_Data_Point ifInfoTable_get_next_data_point;

#endif                          /* IFINFOTABLE_H */
