/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "public.h"
#include "mib.h"
#include "trapNode.h"

extern const oid snmptrap_oid[];
extern const size_t snmptrap_oid_len;

const oid	trapNode_oid[]		= {TRAP_REPORT_NODE};
const oid	trapType_oid[]		= {TRAP_INFO_TYPE_OID};
const oid	trapLevel_oid[] 	= {TRAP_INFO_LEVEL_OID};
const oid	trapTime_oid[]		= {TRAP_INFO_TIME_OID};
const oid	trapReason_oid[]	= {TRAP_INFO_REASON_OID};

int send_trap_api(trapinfo_t *inf)
{
    netsnmp_variable_list *var_list = NULL;

    snmp_varlist_add_variable(&var_list,
                              snmptrap_oid, snmptrap_oid_len,
                              ASN_OBJECT_ID,
                              trapNode_oid, sizeof(trapNode_oid));

    /*
     * Add any objects from the trap definition
     */
    snmp_varlist_add_variable(&var_list,
                              trapType_oid, OID_LENGTH(trapType_oid),
                              ASN_INTEGER,
                              (void *)&(inf->trapType),
                              sizeof(inf->trapType));
    snmp_varlist_add_variable(&var_list,
                              trapLevel_oid, OID_LENGTH(trapLevel_oid),
                              ASN_INTEGER,
							  (void *)&(inf->trapLevel),
						      sizeof(inf->trapLevel));
    snmp_varlist_add_variable(&var_list,
                              trapTime_oid, OID_LENGTH(trapTime_oid),
                              ASN_TIMETICKS,
							  (void *)&(inf->trapTime),
							  sizeof(inf->trapTime));
    snmp_varlist_add_variable(&var_list,
                              trapReason_oid, OID_LENGTH(trapReason_oid),
                              ASN_OCTET_STR,
							  (void *)(inf->trapReason),
							  strlen(inf->trapReason));

    /*
     * Send the trap to the list of configured destinations
     *  and clean up
     */
    send_v2trap(var_list);
    snmp_free_varbind(var_list);

    return SNMP_ERR_NOERROR;
}
