= syslog使用方法
:toc: left

== 简介
  syslog是Linux下默认的日志守护进程。syslog按照标准格式记录日志，任何进程都可以使用（linux系统
预定义了一些日志模块，如：mail、kern等）。
  rsyslog是linux下syslog的升级版，用法是一样的

== 配置
. 配置文件：`/etc/syslog.conf`
. 配置格式
....
facility.level        action
....
说明：
facility表示模块
level表示日志级别
action表示对日志的处理

..  *facility配置说明*
....
kern     内核信息，首先通过 klogd 传递；
user     用户进程；
mail     邮件；
daemon   后台进程；
authpriv 授权信息；
syslog   系统日志；
lpr      打印信息；
news     新闻组信息；
uucp     由uucp生成的信息
cron     计划和任务信息。
mark     syslog 内部功能用于生成时间戳
local0----local7   与自定义程序使使用
....
.. *level配置说明*
....
emerg 或 panic   该系统不可用（已经弃用，尽量不用）
alert            需要立即被修改的条件（紧急消息）
crit             阻止某些工具或子系统功能实现的错误条件（重要消息）
err              阻止工具或某些子系统部分功能实现的错误条件（出错消息）
warning          预警信息（警告消息）
notice           具有重要性的普通条件（普通但重要的消息）
info             提供信息的消息（通知性消息）
debug            不包含函数条件或问题的其他信息（调试级-信息量最多）
none             没有重要级，通常用于排错（不记录任何日志消息）
*                所有级别，除了none
....
.. *action配置,举例说明*
....
#把所有级别高于err和kern模块所有日志打印到 串口
*.err;kern.*  /dev/console

#把日志写到/var/log/messages文件中，除了mail/authpriv模块的日志
*.info;mail.none;authpriv.none          /var/log/messages

#把authpriv模块的日志写到指定文件/var/log/secure中
authpriv.*                              /var/log/secure

#把mail模块的日志写到指定文件/var/log/maillog中
mail.*                                  /var/log/maillog

#指定action为* ，表示所有用户. 把所有emerg级别的日志通知给每个登录的用户
*.emerg                                 *
#指定action为远程主机，表示把日志发送到指定主机。用@表示，例如：@x.x.x.x:port
*.emerg                                 @arpa.berkeley.edu

#指定action为特定用户
*.alert                                 root,eric

#用户自定义日志
local0.*                          /var/log/local0.log
local1.*                          /var/log/local1.log
local2.*                          /var/log/local2.log
local3.*                          /var/log/local3.log
local4.*                          /var/log/local4.log
local5.*                          /var/log/local5.log
local6.*                          /var/log/local6.log
local7.*                          /var/log/local7.log
....
== 接口
- 接口函数

[source,c]
----
#include <syslog.h>

void closelog(void);
void openlog(const char *ident, int logopt, int facility);
void syslog(int priority, const char *message, ...);
----

* *使用说明*
** 编写程序时，_openlog_和_closelog_可以手动调用，也可以不调用。如果程序中
没有调用，那么首次执行syslog时，会自动调用。
** _syslog_函数，第一个参数填级别,后面是就是我们熟悉的类似printf的格式化字符串.
* 常用宏

.facility定义日志模块
[source,c]
....
/* facility codes */
#define	LOG_KERN	(0<<3)	/* kernel messages */
#define	LOG_USER	(1<<3)	/* random user-level messages */
#define	LOG_MAIL	(2<<3)	/* mail system */
#define	LOG_DAEMON	(3<<3)	/* system daemons */
#define	LOG_AUTH	(4<<3)	/* security/authorization messages */
#define	LOG_SYSLOG	(5<<3)	/* messages generated internally by syslogd */
#define	LOG_LPR		(6<<3)	/* line printer subsystem */
#define	LOG_NEWS	(7<<3)	/* network news subsystem */
#define	LOG_UUCP	(8<<3)	/* UUCP subsystem */
#define	LOG_CRON	(9<<3)	/* clock daemon */
#define	LOG_AUTHPRIV	(10<<3)	/* security/authorization messages (private) */
#define	LOG_FTP		(11<<3)	/* ftp daemon */

	/* other codes through 15 reserved for system use */
#define	LOG_LOCAL0	(16<<3)	/* reserved for local use */
#define	LOG_LOCAL1	(17<<3)	/* reserved for local use */
#define	LOG_LOCAL2	(18<<3)	/* reserved for local use */
#define	LOG_LOCAL3	(19<<3)	/* reserved for local use */
#define	LOG_LOCAL4	(20<<3)	/* reserved for local use */
#define	LOG_LOCAL5	(21<<3)	/* reserved for local use */
#define	LOG_LOCAL6	(22<<3)	/* reserved for local use */
#define	LOG_LOCAL7	(23<<3)	/* reserved for local use */
....

.level定义日志级别
[source,c]
....
#define	LOG_EMERG	0	/* system is unusable */
#define	LOG_ALERT	1	/* action must be taken immediately */
#define	LOG_CRIT	2	/* critical conditions */
#define	LOG_ERR		3	/* error conditions */
#define	LOG_WARNING	4	/* warning conditions */
#define	LOG_NOTICE	5	/* normal but significant condition */
#define	LOG_INFO	6	/* informational */
#define	LOG_DEBUG	7	/* debug-level messages */
....
== 用户自定义用法
这里介绍如何使用,用户自定义的日志.例如,有如下配置文件

*syslog.conf*
....
local0.*      /var/log/local0.log
local1.*      /var/log/local1.log
....
我们想把程序local0的日志写入在 /var/log/local0.log

我们想把程序local1的日志写入在 /var/log/local1.log

.方法1
====
. 在程序中显式调用openlog
. openlog的第三个参数,指定为 LOG_LOGCAL0

例如:
[source,c]
openlog("ident",LOG_CONS|LOG_PID,LOG_LOCAL0)
====
.方法2
====
. 程序中无需调用openlog和closelog
. 把syslog调用,的第一个参数写成:facility+level的形式

例如:
[source,c]
syslog(LOG_LOCAL0+LOG_INFO,"这个日志指向,local0的配置")
syslog(LOG_LOCAL1+LOG_INFO,"这个日志指向,local1的配置")
syslog(LOG_LOCAL2+LOG_INFO,"这个日志指向,local2的配置")

====
